language: python
sudo: false
branches:
  only:
    - master
python:
  - 3.6
install:
  - pip install pipenv
  - pipenv install --dev
before_script:
  - pipenv run python manage.py migrate
  - pipenv run python manage.py collectstatic --no-input
script:
  - pipenv run coverage run manage.py test -v 3
after_success:
  - pipenv run coveralls
addons:
  code_climate:
    repo_token: c42dbb6e9c46bd32673908a66bb1c50908dd52040cb395a9ca375b153d971716
