# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('F', 'Hall of Fame (não utilizará limites/fraquia)'), ('S', 'Hall of Shame (utilizará limites/franquia)')], max_length=1, verbose_name='Categoria')),
                ('name', models.CharField(max_length=128, verbose_name='Nome do provedor')),
                ('url', models.URLField(verbose_name='URL do provedor')),
                ('source', models.URLField(verbose_name='URL da fonte da informação')),
                ('other', models.CharField(max_length=140, verbose_name='Observações')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('abbr', models.CharField(max_length=2, verbose_name='Sigla')),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='coverage',
            field=models.ManyToManyField(to='core.State', verbose_name='Cobertura'),
        ),
    ]
