# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_states_fixtures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'Provedor', 'verbose_name_plural': 'Provedores'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='provider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='other',
            field=models.CharField(blank=True, max_length=140, verbose_name='Observações'),
        ),
    ]
