# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160413_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='status',
            field=models.CharField(choices=[('N', 'Aguardando moderação'), ('D', 'Em discussão'), ('P', 'Publicado'), ('R', 'Recusado')], default='N', max_length=1, verbose_name='Status'),
        ),
    ]
