# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160416_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='published',
        ),
    ]
