# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_provider_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='moderation',
            field=models.TextField(blank=True, verbose_name='Comentários da moderação'),
        ),
    ]
