# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_convert_moderation_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='moderation',
        ),
    ]
