# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 20:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_provider_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 21, 20, 55, 31, 220419, tzinfo=utc), verbose_name='Editado em'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='moderation_reason',
            field=models.CharField(choices=[('', 'Não se aplica'), ('R', 'Provedor repetido'), ('N', 'Fonte não encontrada (404)'), ('I', 'Fonte com informações imprecisas ou erradas'), ('A', 'Fonte não acessível (ex.: requer login)'), ('P', 'Fonte é comunicação privada (ex.: chat ou suporte)'), ('O', 'Outros')], default='', max_length=1, verbose_name='Motivo'),
        ),
    ]
