# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160421_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='edited_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Provider'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='moderation_reason',
            field=models.CharField(blank=True, choices=[('', 'Não se aplica'), ('R', 'Provedor repetido'), ('N', 'Fonte não encontrada (404)'), ('I', 'Fonte com informações imprecisas ou erradas'), ('A', 'Fonte não acessível (ex.: requer login)'), ('P', 'Fonte é comunicação privada (ex.: chat ou suporte)'), ('O', 'Outros')], default='', max_length=1, verbose_name='Motivo'),
        ),
    ]
